### PR TITLE
Mod integration update

### PR DESCRIPTION
**Pull request by bculkin2442**
Update of mod integration for IC2, MFR and GT. See commits for details on additions.

### CODE REVIEW

**Comment by Yulife** [comment]
Why not both? :)

**Comment by Dream-Master** [comment]
@Yulife  Only as Info.

**Comment by Yulife** [comment]
Stan would be pulling appropriate PRs but he is not active atm :)

**Comment by stanhebben** [comment]
I do accept good PR's, just .. I don't watch the repo very closely these days. (Still in working overtime mode, unfortunately)

As for the GT support, it will be removed soon, with DreamMaster's version becoming the official source of GT mod support. @Dream-Master does your support include everything from this PR?

For the IC2 version update, everything looks good, I will include this, hopefully find some time to test this soon, and ship a new MineTweaker version.

**Comment by Dream-Master** [comment]
@stanhebben 
@bculkin2442 

I think my Java Knowledge isnt that big so when bculkin2442 make all code already maybe take it into minetweaker. Only the new GT Unofficial Machines are missing like the Fusion reactor, Distillation tower ...
I make only this mod because i want to using all GT machines but when it got be part of Minetweaker it would be fine too for me.

**Pull request merged**
