### PR TITLE
Catch Throwables when dumping recipes. Fixes #306.

### LINKED ISSUE #306: [bug] FTB Infinity Evolved Expert causes NPE when dumping all recipes with /mt recipes
Hi again,

I get the following (unhelpful) error when using /mt recipes:

[15:04:50] [Server thread/ERROR]: Couldn't process command: 'mt recipes' 
java.lang.NullPointerException 
[15:04:50] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

### Interesting stuff from the logs

Before writing any recipe commands to the log, MT writes this:

    // unknown recipe type for null
    // unknown recipe type for <Forestry:core>
    // unknown recipe type for <Forestry:core>
    // unknown recipe type for <Forestry:apiculture>
    // unknown recipe type for <Forestry:apiculture:2>
    // unknown recipe type for <Forestry:apiculture:1>
    // unknown recipe type for <Forestry:arboriculture>
    // unknown recipe type for <Forestry:engine:1>
    // unknown recipe type for <Forestry:engine:2>
    // unknown recipe type for <Forestry:engine:4>
    // unknown recipe type for <Forestry:factory>
    // unknown recipe type for <Forestry:factory:1>
    // unknown recipe type for <Forestry:factory:2>
    // unknown recipe type for <Forestry:factory2>
    // unknown recipe type for <Forestry:factory:3>
    // unknown recipe type for <Forestry:factory:4>
    // unknown recipe type for <Forestry:factory2:1>
    // unknown recipe type for <Forestry:factory:5>
    // unknown recipe type for <Forestry:factory:6>
    // unknown recipe type for <Forestry:factory:7>
    // unknown recipe type for <Forestry:lepidopterology>
    // unknown recipe type for <Forestry:mail>
    // unknown recipe type for <Forestry:mail:1>
    // unknown recipe type for <Forestry:engine>
    // unknown recipe type for <Forestry:engine:3>

These are from UnknownRecipe.java and are probably unrelated to the bug:

https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-API/src/main/java/minetweaker/api/recipes/UnknownRecipe.java#L44

The final recipe it outputs (which unfortunately is the one *before* the one causing the NPE) is:

    recipes.addShaped(<MagicBees:item.manasteelGrafter>, [[null, null, <Botania:manaResource>], [null, <minecraft:stick>, null], [<minecraft:stick>, null, null]]);

This at least narrows it down to a shaped, non oredict recipe that's broken.

### Poking around at the code

I am not sure why there's no stack trace dumped to the logs for this NPE. Tracing the code backwards shows that the complexity is in RecipeConverter.toCraftingRecipe and ShapedRecipe.toCommandString:

https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-API/src/main/java/minetweaker/MineTweakerImplementationAPI.java#L206
https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Main/src/main/java/minetweaker/mc1710/recipes/MCRecipeManager.java#L76
https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Main/src/main/java/minetweaker/mc1710/recipes/RecipeConverter.java#L131

https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-API/src/main/java/minetweaker/api/recipes/ShapedRecipe.java#L232

It seems there's already some prior art for catching Throwable elsewhere in the main API file:

https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-API/src/main/java/minetweaker/MineTweakerImplementationAPI.java#L101

Now, I'm guessing that there's a broken recipe somewhere in all the tweaking that the FTB folks have done for IE:E, and this is not the fault of MineTweaker per se. But! it would sure be nice to be able to track this down and fix it, so I can dump all the recipes. As such I'd like to propose a PR to wrap bits of recipe generation in a try/catch too.

### PR DESCRIPTION
**Pull request by fluffle**
See #306 for the whys.

### CODE REVIEW

**Comment by jaredlll08** [comment]
What happens if the recipe is null? That would still crash, I suggest you add an "else" in the catch, then I'll accept it

**Comment by fluffle** [comment]
It's probably best to make sure every code path actually logs an error, yes :-)

PTAL?

**Comment by jaredlll08** [comment]
PTAL?

**Comment by fluffle** [comment]
Please take a look ;-)

**Comment by jaredlll08** [comment]
looks good

**Comment by fluffle** [comment]
Nope, you're right. I am a terrible person: I did not recompile to test it after making the change that @jaredlll08 asked. Sorry to break things, that's kinda not cool :-(

**Comment by jaredlll08** [comment]
@fluffle please, really, don't worry :) it was a small thing, and was caught before a release was made :)

**Pull request merged**
